# Generated by Django 4.2 on 2024-06-16 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='securities', to=settings.AUTH_USER_MODEL),
        ),
    ]
